/**
 * Un angle par montant (RECETTE §6.2) : chaque page porte le seuil réel qui lui est propre,
 * son H2, son paragraphe et ses questions. Les chiffres viennent du moteur, jamais écrits à la main.
 */
import { compute, monthlyFromHourly, hourlyFromMonthly, residentTax, sdlMonth } from './engine/sg';
import P from '../data/params-2026.json';
import { grossFromMomMedian } from './tables';
import { formatMoney as $, formatPercent as pct } from './format';

export interface Angle { title: string; description: string; h1: string; h2: string; p: string; h2b: string; p2: string; faqs: Array<{ q: string; a: string }> }
const c = (m: number, o: Partial<Parameters<typeof compute>[0]> = {}) => compute({ monthly: m, age: 30, status: 'SC', ...o });
const W = P.wages;

export function monthlyAngle(m: number): Angle {
  const r = c(m); const pr = c(m, { status: 'SPR1_GG' }); const fo = c(m, { status: 'FOREIGNER' }); const o58 = c(m, { age: 58 });
  const A: Record<number, () => Angle> = {
    1800: () => ({
      title: `$1,800 Salary Singapore 2026: Take-Home, CPF, LQS Floor`, description: `$1,800 a month in Singapore: ${$(r.takeHomeMonthly)} take-home after CPF, no income tax, and why it is now the Local Qualifying Salary floor for local employees in 2026.`,
      h1: `$1,800 a month in Singapore: take-home pay at the new LQS`, h2: 'The salary that became a legal floor on 1 July 2026',
      p: `Since 1 July 2026, ${$(1800)} is the Local Qualifying Salary: the minimum a firm must pay a full-time local employee for that person to count towards its foreign worker quota. It replaced a floor of ${$(W.lqs_previous)}. A citizen aged 30 paid exactly this amount contributes ${$(r.monthly.employee)} to CPF and takes home ${$(r.takeHomeMonthly)} a month, while the employer adds ${$(r.monthly.employer)}. No income tax is due: twelve months of salary come to ${$(21600)}, and after the earned income relief and the CPF relief the chargeable income is ${$(r.annual.chargeable)}, inside the tax-free first ${$(20000)}. At this level the CPF split is worth watching, because ${$(r.allocation.oa)} a year goes to the Ordinary Account, which is what many young workers use later for an HDB flat.`,
      h2b: 'Workfare on top of the salary',
      p2: `Workers aged 30 and above earning this salary are within the income range of the Workfare Income Supplement, which the government pays partly in cash and partly into CPF, without any deduction from pay. It does not appear on the payslip and is not taxable. On MOM’s hourly formula, ${$(1800)} corresponds to ${$(hourlyFromMonthly(1800), 2)} an hour on a 44-hour week.`,
      faqs: [
        { q: 'Is $1,800 the minimum wage in Singapore?', a: `Not for everyone. ${$(1800)} is the Local Qualifying Salary from 1 July 2026, the pay a firm must give a full-time local worker for that worker to count in its foreign worker quota. Sectors covered by a Progressive Wage Model have their own minimums, and there is no single national minimum wage.` },
        { q: 'Do I pay income tax on $1,800 a month?', a: `No. A year at ${$(1800)} a month is ${$(21600)}. After the ${$(1000)} earned income relief and the CPF relief of ${$(r.annual.reliefs.cpf)}, chargeable income is ${$(r.annual.chargeable)}, below the ${$(20000)} on which the resident rate is 0 %. IRAS may still ask you to file a return.` },
        { q: 'How much CPF goes into my account on $1,800?', a: `${$(r.monthly.total)} a month in total: ${$(r.monthly.employee)} deducted from your pay and ${$(r.monthly.employer)} paid by your employer. At 30, about 62 % goes to the Ordinary Account, 16 % to the Special Account and 22 % to MediSave, which is ${$(r.allocation.oa)}, ${$(r.allocation.sa)} and ${$(r.allocation.ma)} over a year.` },
      ],
    }),
    2500: () => ({
      title: `$2,500 Salary Singapore 2026: Take-Home Pay and First Tax`, description: `$2,500 a month in Singapore leaves ${$(r.takeHomeMonthly)} after CPF and a first small tax bill of ${$(r.annual.tax)}: where income tax starts, and what a new PR takes home instead.`,
      h1: `$2,500 a month: take-home pay and the point where tax starts`, h2: 'The salary where income tax begins',
      p: `${$(2500)} a month is roughly where a Singapore employee starts to owe income tax. Twelve months give ${$(30000)} of employment income. The earned income relief takes off ${$(1000)} and the CPF relief ${$(r.annual.reliefs.cpf)}, leaving ${$(r.annual.chargeable)} of chargeable income: ${$(r.annual.chargeable - 20000)} above the tax-free band, taxed at 2 %. The bill for YA ${P.tax.year_of_assessment} is ${$(r.annual.tax)}, about ${$(r.annual.tax / 12)} a month, small enough that many people forget it until the notice arrives. The payslip itself shows only CPF: ${$(r.monthly.employee)} from the employee, leaving ${$(r.takeHomeMonthly)} of take-home pay. A first-year PR on graduated rates keeps ${$(pr.takeHomeMonthly)}, because only 5 % is deducted, but pays a little more tax, ${$(pr.annual.tax)}, since the CPF relief is smaller. Anyone at this level who receives a bonus, even a small one, will see it taxed at 2 % rather than the 0 % of the first band.`,
      h2b: 'Part-time or full-time',
      p2: `At ${$(2500)} for a full-time week, the MOM hourly basic rate is ${$(hourlyFromMonthly(2500), 2)}. Employees who are not workmen and earn up to ${$(W.nonworkman_ot_ceiling)} are covered by Part IV of the Employment Act; above it they are not, so overtime and rest-day pay depend on the contract. At ${$(2500)} a non-workman is still covered.`,
      faqs: [
        { q: 'How much tax do I pay on $2,500 a month in Singapore?', a: `About ${$(r.annual.tax)} for the year if you are a citizen aged 30 with no other reliefs. Your chargeable income after the earned income relief and CPF relief is ${$(r.annual.chargeable)}, and only the part above ${$(20000)} is taxed, at 2 %. There is no monthly withholding: IRAS bills you the following year.` },
        { q: 'What is the take-home pay on $2,500 for a new PR?', a: `${$(pr.takeHomeMonthly)} a month in the first year of PR status on the default graduated rates, since only 5 % of salary goes to CPF, against ${$(r.takeHomeMonthly)} for a citizen. In the second year the employee rate rises to 15 %, and from the third year to 20 %, like a citizen.` },
        { q: 'Am I entitled to overtime pay on $2,500?', a: `Yes, if your contract has overtime and you are covered by Part IV of the Employment Act, which applies to non-workmen earning up to ${$(W.nonworkman_ot_ceiling)} and workmen up to ${$(W.workman_ot_ceiling)}. Overtime is paid at 1.5 times the hourly basic rate, ${$(hourlyFromMonthly(2500), 2)} at this salary, so ${$(hourlyFromMonthly(2500) * 1.5, 2)} an hour.` },
      ],
    }),
    3000: () => ({
      title: `$3,000 Salary Singapore 2026: Take-Home $2,400 After CPF`, description: `$3,000 a month in Singapore: ${$(r.takeHomeMonthly)} take-home after CPF, ${$(r.annual.tax)} of tax a year, and how it compares with the S Pass qualifying salary of ${$(W.spass_min)} a month.`,
      h1: `$3,000 a month in Singapore: take-home pay and CPF`, h2: 'A common first salary, just under the S Pass threshold',
      p: `${$(3000)} is a frequent starting salary for diploma holders and the first rung of many office jobs. It also sits just below the ${$(W.spass_min)} a month that the Ministry of Manpower has required for new S Pass applications since September 2025, which means a foreign mid-skilled worker cannot be hired at this salary. For a local employee aged 30, CPF takes ${$(r.monthly.employee)} and the take-home pay is ${$(r.takeHomeMonthly)}. The employer adds ${$(r.monthly.employer)} of CPF and ${$(sdlMonth(3000), 2)} of Skills Development Levy, so the job costs ${$(r.annual.employerCost)} a year. Income tax is light: ${$(r.annual.tax)} for YA ${P.tax.year_of_assessment}, on a chargeable income of ${$(r.annual.chargeable)}. After tax and CPF, the employee keeps ${$(r.annual.net)} a year, while ${$(r.annual.cpfTotal)} builds up in CPF, most of it in the Ordinary Account that many young workers later draw on for an HDB flat.`,
      h2b: 'What a raise to $3,500 would change',
      p2: `A ${$(500)} raise adds ${$(c(3500).takeHomeMonthly - r.takeHomeMonthly)} to monthly take-home pay and ${$(c(3500).annual.tax - r.annual.tax)} to the annual tax, because the extra income crosses into the 3.5 % band. The employer’s cost rises by ${$(c(3500).annual.employerCost - r.annual.employerCost)} a year.`,
      faqs: [
        { q: 'Is $3,000 a good salary in Singapore?', a: `It is below the median. MOM’s median gross monthly income for full-time residents was ${$(W.mom_median_2025)} in 2025, including employer CPF, which corresponds to a salary of about ${$(Math.round(grossFromMomMedian / 100) * 100)}. ${$(3000)} is typical for a first job after a diploma or in retail and service roles, and leaves ${$(r.takeHomeMonthly)} a month after CPF.` },
        { q: 'Can a foreigner be hired on $3,000 a month?', a: `Not on an S Pass or Employment Pass: new S Pass applications have required at least ${$(W.spass_min)} a month since 1 September 2025, higher in financial services and for older candidates, and the Employment Pass requires at least ${$(W.ep_min)}. Work Permits have no qualifying salary but are limited to specific sectors and nationalities.` },
        { q: 'What does $3,000 cost my employer?', a: `${$(r.annual.employerCost)} a year for a citizen aged 30: ${$(36000)} of salary, ${$(r.annual.cpfEmployer)} of employer CPF and ${$(r.annual.sdl, 2)} of Skills Development Levy. Insurance, bonuses and other benefits come on top and depend on the company, and a foreign hire at this salary is not possible on an S Pass.` },
      ],
    }),
    3500: () => ({
      title: `$3,500 Salary Singapore 2026: Take-Home and 3.5 % Band`, description: `On $3,500 a month in Singapore you take home ${$(r.takeHomeMonthly)} after CPF and reach the 3.5 % tax band, ${$(r.annual.tax)} for YA 2027. With the S Pass line and the PR rates.`,
      h1: `$3,500 a month: take-home pay, CPF and the 3.5 % tax band`, h2: 'Crossing into the 3.5 % band',
      p: `At ${$(3500)} a month, chargeable income for the year reaches ${$(r.annual.chargeable)} once the earned income relief and the CPF relief are deducted. That is past ${$(30000)}, the point where Singapore’s resident rate moves from 2 % to 3.5 %: the first ${$(20000)} is free, the next ${$(10000)} costs ${$(200)}, and the remaining ${$(r.annual.chargeable - 30000)} is taxed at 3.5 %. The YA ${P.tax.year_of_assessment} bill totals ${$(r.annual.tax)}, an effective rate of ${pct(r.annual.effectiveTaxRate)} on gross salary. The payslip shows ${$(r.monthly.employee)} of employee CPF and a take-home of ${$(r.takeHomeMonthly)}. The salary is also just above the S Pass qualifying salary of ${$(W.spass_min)}, so it is a level at which local and foreign mid-skilled candidates compete for the same roles; for the employer, a foreign S Pass holder costs no CPF but a foreign worker levy.`,
      h2b: 'Aged 58 on the same salary',
      p2: `An employee aged 58 contributes 18 % instead of 20 %, ${$(o58.monthly.employee)} a month, and takes home ${$(o58.takeHomeMonthly)}. From January 2027 the rate for that age rises to 19 %, reducing take-home pay by ${$(o58.takeHomeMonthly - c(3500, { age: 58, year: 2027 }).takeHomeMonthly)} a month.`,
      faqs: [
        { q: 'How much income tax is due on $3,500 a month?', a: `${$(r.annual.tax)} for YA ${P.tax.year_of_assessment} for a citizen aged 30 with the automatic reliefs. Chargeable income is ${$(r.annual.chargeable)}: 0 % on the first ${$(20000)}, 2 % on the next ${$(10000)} and 3.5 % on the rest. That is about ${$(r.annual.tax / 12)} a month to put aside, since tax is not deducted from salary.` },
        { q: 'What is the take-home pay on $3,500 for a foreigner?', a: `The full ${$(3500)}, since foreign employees do not contribute to CPF. A resident foreigner pays more income tax, ${$(fo.annual.tax)} rather than ${$(r.annual.tax)}, because without CPF there is no CPF relief; a non-resident would pay 15 % of gross salary, ${$(3500 * 12 * 0.15)} a year.` },
        { q: 'Is $3,500 enough to hire on an S Pass?', a: `It clears the general S Pass qualifying salary of ${$(W.spass_min)} a month for new applications since 1 September 2025, but not the higher level for financial services, ${$(W.spass_min_finance)}, and the qualifying salary rises with the candidate’s age. The S Pass also requires a levy and a quota, checked by MOM.` },
      ],
    }),
    4000: () => ({
      title: `$4,000 Salary Singapore 2026: Take-Home $3,200 and CPF Split`, description: `$4,000 a month in Singapore: ${$(r.takeHomeMonthly)} take-home, ${$(r.monthly.total)} into CPF every month and how it splits between the Ordinary, Special and MediSave accounts.`,
      h1: `$4,000 a month in Singapore: take-home pay and where CPF goes`, h2: 'Where $1,480 a month of CPF ends up',
      p: `On ${$(4000)} a month, ${$(r.monthly.total)} goes into CPF every month: ${$(r.monthly.employee)} from the salary and ${$(r.monthly.employer)} from the employer. The take-home pay is ${$(r.takeHomeMonthly)}. What happens to the CPF matters as much as the take-home, and it depends on age. At 30, the CPF Board credits about 62 % to the Ordinary Account, which can pay an HDB mortgage, 16 % to the Special Account and 22 % to MediSave: over a year ${$(r.allocation.oa)}, ${$(r.allocation.sa)} and ${$(r.allocation.ma)}. At 48 the Ordinary Account share falls to about 51 %, and above 55 to about 35 %, while the Retirement Account and MediSave take more. Someone paying a housing loan from CPF on this salary should check that the Ordinary Account inflow still covers the instalment in their fifties. Income tax for YA ${P.tax.year_of_assessment} is ${$(r.annual.tax)}.`,
      h2b: 'Graduated rates for a new PR',
      p2: `A first-year PR on graduated rates contributes 5 % and takes home ${$(pr.takeHomeMonthly)}, ${$(pr.takeHomeMonthly - r.takeHomeMonthly)} more than a citizen, while the employer pays 4 %. Opting into full employer rates costs the PR nothing in take-home pay and adds ${$(c(4000, { status: 'SPR1_FG' }).monthly.employer - pr.monthly.employer)} a month to their CPF.`,
      faqs: [
        { q: 'How much goes to my Ordinary Account on $4,000 a month?', a: `About ${$(r.allocation.oa / 12)} a month if you are 30, ${$(r.allocation.oa)} over a year. The Ordinary Account receives what is left after MediSave and the Special Account are credited, around 62 % of the total contribution below age 35, less as you get older.` },
        { q: 'What is $4,000 a month after tax in Singapore?', a: `${$(r.annual.net)} a year after employee CPF and income tax, or about ${$(r.annual.net / 12)} a month, for a citizen aged 30. Monthly take-home pay is ${$(r.takeHomeMonthly)}; the income tax of ${$(r.annual.tax)} is billed the following year and should be set aside, about ${$(r.annual.tax / 12)} a month.` },
        { q: 'How much does my employer pay in CPF on $4,000?', a: `${$(r.monthly.employer)} a month, 17 % of salary, for an employee aged 55 or below who is a citizen or a PR from the third year. For a first-year PR on graduated rates it is ${$(pr.monthly.employer)}, and nothing for a foreign employee.` },
      ],
    }),
    4500: () => ({
      title: `$4,500 Salary Singapore 2026: Take-Home, SDL Cap, Overtime`, description: `$4,500 a month in Singapore: ${$(r.takeHomeMonthly)} take-home, the 7 % tax band, the Skills Development Levy cap and the last salary at which workmen get statutory overtime.`,
      h1: `$4,500 a month: take-home pay and three thresholds`, h2: 'Three rules that stop at $4,500',
      p: `${$(4500)} a month is a threshold in three separate rules. Under Part IV of the Employment Act, workmen earning up to ${$(W.workman_ot_ceiling)} are entitled to statutory overtime at 1.5 times the hourly rate, limits on working hours and rest days; a technician promoted to ${$(4600)} loses that protection unless the contract keeps it. For the employer, the Skills Development Levy reaches its cap of ${$(P.sdl.max, 2)} at exactly ${$(P.sdl.wage_cap)}, since it is 0.25 % of the first ${$(P.sdl.wage_cap)} of monthly wages. And for tax, chargeable income crosses ${$(40000)}, where the resident rate moves from 3.5 % to 7 %: at this salary it is ${$(r.annual.chargeable)}. The payslip is simpler: ${$(r.monthly.employee)} of CPF, ${$(r.takeHomeMonthly)} of take-home pay, with the employer adding ${$(r.monthly.employer)} to CPF.`,
      h2b: 'The 7 % band in practice',
      p2: `Every extra dollar of chargeable income above ${$(40000)} costs 7 cents of tax, but on salary each extra dollar also brings 20 cents of CPF relief, so the tax on a dollar of salary is 5.6 cents. The YA ${P.tax.year_of_assessment} bill at ${$(4500)} is ${$(r.annual.tax)}.`,
      faqs: [
        { q: 'Do I get overtime pay on $4,500 a month?', a: `If you are a workman, yes: Part IV of the Employment Act covers workmen earning up to ${$(W.workman_ot_ceiling)} a month, with overtime at 1.5 times the hourly basic rate, ${$(hourlyFromMonthly(4500) * 1.5, 2)} at this salary. Non-workmen are covered only up to ${$(W.nonworkman_ot_ceiling)}, so an office employee on ${$(4500)} depends on the contract.` },
        { q: 'What is the tax on $4,500 a month in Singapore?', a: `${$(r.annual.tax)} for YA ${P.tax.year_of_assessment}. Chargeable income after the earned income relief and CPF relief is ${$(r.annual.chargeable)}; tax is ${$(550)} on the first ${$(40000)} plus 7 % of the ${$(r.annual.chargeable - 40000)} above. The effective rate is ${pct(r.annual.effectiveTaxRate)} of gross salary, and it is billed once a year.` },
        { q: 'How much SDL does an employer pay on $4,500?', a: `${$(P.sdl.max, 2)} a month, the maximum, since the levy is 0.25 % of the first ${$(P.sdl.wage_cap)} of monthly wages. Any salary at or above ${$(P.sdl.wage_cap)} pays the same ${$(P.sdl.max, 2)}; on ${$(3000)} it would be ${$(sdlMonth(3000), 2)}. The levy is paid by the employer only, with the CPF submission.` },
      ],
    }),
    5000: () => ({
      title: `$5,000 Salary Singapore 2026: Take-Home $4,000, Tax $1,040`, description: `$5,000 a month in Singapore leaves ${$(r.takeHomeMonthly)} after CPF; YA 2027 tax is ${$(r.annual.tax)}. Compared for citizens, new PRs and foreigners, with the employer's full cost.`,
      h1: `$5,000 a month in Singapore: take-home pay for citizens, PRs and foreigners`, h2: 'One salary, three take-home figures',
      p: `${$(5000)} a month is the round figure most people use to picture a Singapore salary, and it produces three different take-home figures depending on status. A citizen aged 30 contributes 20 % to CPF and takes home ${$(r.takeHomeMonthly)}. A permanent resident in the first year of PR status, on graduated rates, contributes 5 % and takes home ${$(pr.takeHomeMonthly)}. A foreigner on an Employment Pass, who does not contribute to CPF, takes home the full ${$(5000)}. The income tax runs the other way: ${$(r.annual.tax)} for the citizen, whose CPF relief lowers taxable income, ${$(fo.annual.tax)} for a resident foreigner, who has no CPF relief. Over a year, the citizen keeps ${$(r.annual.net)} in cash and ${$(r.annual.cpfTotal)} in CPF, the foreigner ${$(fo.annual.net)} in cash and nothing in CPF. ${$(5000)} is also below the Employment Pass qualifying salary of ${$(W.ep_min)}.`,
      h2b: 'The employer’s side',
      p2: `For the employer, the citizen costs ${$(r.annual.employerCost)} a year with employer CPF and SDL, the foreigner ${$(fo.annual.employerCost)}. The difference is the employer CPF, which becomes part of the citizen’s savings.`,
      faqs: [
        { q: 'What is the take-home pay for a $5,000 salary in Singapore?', a: `${$(r.takeHomeMonthly)} for a citizen or PR from the third year aged 55 or below, after ${$(r.monthly.employee)} of employee CPF. A first-year PR on graduated rates takes home ${$(pr.takeHomeMonthly)} and a foreigner ${$(5000)}. Income tax is not deducted from the salary and is billed the following year.` },
        { q: 'How much income tax on a $60,000 salary for a citizen?', a: `${$(r.annual.tax)} for YA ${P.tax.year_of_assessment}. The earned income relief of ${$(1000)} and the CPF relief of ${$(r.annual.reliefs.cpf)} bring chargeable income to ${$(r.annual.chargeable)}, taxed at ${$(550)} on the first ${$(40000)} plus 7 % above. Other reliefs, for a spouse or children, lower it further.` },
        { q: 'Can a foreigner get an Employment Pass on $5,000?', a: `Not for a new application: the Employment Pass qualifying salary has been ${$(W.ep_min)} a month since January 2025, ${$(W.ep_min_finance)} in financial services, and it increases with the candidate’s age. A ${$(5000)} offer can fit an S Pass, whose qualifying salary is ${$(W.spass_min)}, subject to quota and levy.` },
      ],
    }),
    6000: () => ({
      title: `$6,000 Salary Singapore 2026: Take-Home, Tax, EP Threshold`, description: `$6,000 a month in Singapore: ${$(r.takeHomeMonthly)} take-home after CPF, ${$(r.annual.tax)} of tax, and what it means next to the Employment Pass qualifying salary of $5,600 a month.`,
      h1: `$6,000 a month: take-home pay just above the Employment Pass line`, h2: 'Above the Employment Pass qualifying salary',
      p: `${$(6000)} a month clears the Employment Pass qualifying salary of ${$(W.ep_min)}, the first stage of MOM’s assessment for foreign professionals, though not the ${$(W.ep_min_finance)} required in financial services, and the threshold rises for older candidates. It is therefore a level at which employers weigh local and foreign hires directly. For a citizen aged 30, CPF takes ${$(r.monthly.employee)} and the take-home pay is ${$(r.takeHomeMonthly)}; the employer adds ${$(r.monthly.employer)}. For an Employment Pass holder, take-home is the full ${$(6000)} and the employer pays no CPF, only SDL of ${$(P.sdl.max, 2)}. Income tax on the year is ${$(r.annual.tax)} for the citizen and ${$(fo.annual.tax)} for a resident foreigner. Another threshold appears on a bonus: at ${$(6000)} a month the Additional Wage ceiling is ${$(r.awCeiling)}, so a bonus of up to five months still attracts CPF in full.`,
      h2b: 'Net of everything',
      p2: `After CPF and tax, the citizen keeps ${$(r.annual.net)} a year, about ${$(r.annual.net / 12)} a month, and accumulates ${$(r.annual.cpfTotal)} in CPF, of which ${$(r.allocation.oa)} in the Ordinary Account at age 30.`,
      faqs: [
        { q: 'Is $6,000 enough for an Employment Pass?', a: `It meets the general qualifying salary of ${$(W.ep_min)} a month for a new application, the first of two stages. The candidate must also pass COMPASS, a points framework on salary, qualifications, workforce diversity and local employment. In financial services the qualifying salary is ${$(W.ep_min_finance)}, and it is higher for older candidates.` },
        { q: 'What is $6,000 a month after tax in Singapore?', a: `${$(r.annual.net)} a year after CPF and income tax for a citizen aged 30, about ${$(r.annual.net / 12)} a month. The take-home pay each month is ${$(r.takeHomeMonthly)}, and the YA ${P.tax.year_of_assessment} tax of ${$(r.annual.tax)} is billed separately, so about ${$(r.annual.tax / 12)} a month should be put aside.` },
        { q: 'How much bonus attracts CPF on $6,000 a month?', a: `Up to ${$(r.awCeiling)} a year. The Additional Wage ceiling is ${$(P.cpf.annual_salary_ceiling)} minus the ${$(72000)} of ordinary wages subject to CPF, so a bonus of up to five months is charged in full. Beyond that amount, the bonus is paid without CPF but is still taxed.` },
      ],
    }),
    7000: () => ({
      title: `$7,000 Salary Singapore 2026: Take-Home and Bonus CPF Limit`, description: `$7,000 a month in Singapore: ${$(r.takeHomeMonthly)} take-home after CPF, ${$(r.annual.tax)} of tax, and why only ${$(r.awCeiling)} of any bonus attracts CPF at this monthly salary.`,
      h1: `$7,000 a month: take-home pay and a tighter bonus ceiling`, h2: 'The bonus ceiling starts to bind',
      p: `At ${$(7000)} a month, ordinary wages subject to CPF total ${$(84000)} over the year, which leaves an Additional Wage ceiling of ${$(r.awCeiling)}. A bonus of two months, ${$(14000)}, attracts CPF in full; a bonus of three months, ${$(21000)}, only on its first ${$(r.awCeiling)}. The part above is paid without CPF deductions, so it reaches the bank account whole, but it is still taxable and earns no CPF relief. On the monthly payslip, the citizen aged 30 contributes ${$(r.monthly.employee)} and takes home ${$(r.takeHomeMonthly)}, while the employer adds ${$(r.monthly.employer)}. Without a bonus, income tax for YA ${P.tax.year_of_assessment} is ${$(r.annual.tax)}; with three months of bonus it rises to ${$(c(7000, { bonus: 21000 }).annual.tax)}, because the bonus lifts chargeable income further into the 7 % band and close to the 11.5 % band that starts at ${$(80000)} of chargeable income. Employees at this salary who are offered a choice between a higher fixed salary and a larger bonus should compare both with the bonus calculator.`,
      h2b: 'What a three-month bonus leaves',
      p2: `Of a ${$(21000)} bonus, the employee pays ${$(c(7000, { bonus: 21000 }).bonusMonth.employee - r.monthly.employee)} of CPF and about ${$(c(7000, { bonus: 21000 }).annual.tax - r.annual.tax)} of extra tax, and keeps the rest, ${$(21000 - (c(7000, { bonus: 21000 }).bonusMonth.employee - r.monthly.employee) - (c(7000, { bonus: 21000 }).annual.tax - r.annual.tax))}.`,
      faqs: [
        { q: 'What is the take-home on $7,000 a month in Singapore?', a: `${$(r.takeHomeMonthly)} for a citizen or PR from the third year aged 55 or below, after ${$(r.monthly.employee)} of employee CPF. A 58-year-old takes home ${$(o58.takeHomeMonthly)}, since the rate falls to 18 %. Tax is not withheld; the annual bill without bonus is ${$(r.annual.tax)}.` },
        { q: 'Why is there no CPF on part of my bonus at $7,000?', a: `Because the Additional Wage ceiling at this salary is ${$(r.awCeiling)}: ${$(P.cpf.annual_salary_ceiling)} minus ${$(84000)} of ordinary wages. CPF applies to the bonus only up to that amount; the rest is paid gross. The ceiling is recomputed at year end if your salary changes.` },
        { q: 'What does a $7,000 employee cost the employer?', a: `${$(r.annual.employerCost)} a year without bonus for a citizen aged 30: ${$(84000)} of salary, ${$(r.annual.cpfEmployer)} of employer CPF and ${$(r.annual.sdl, 2)} of SDL. With a two-month bonus, employer CPF on the bonus adds 17 % of it, since the bonus stays within the Additional Wage ceiling of ${$(r.awCeiling)}.` },
      ],
    }),
    8000: () => ({
      title: `$8,000 Salary Singapore 2026: CPF Ceiling and Take-Home`, description: `$8,000 a month is exactly the CPF ordinary wage ceiling in 2026: ${$(r.takeHomeMonthly)} take-home, maximum CPF of ${$(r.monthly.total)} a month and a ${$(r.awCeiling)} yearly bonus ceiling.`,
      h1: `$8,000 a month: the CPF ceiling and your take-home pay`, h2: 'Exactly at the ordinary wage ceiling',
      p: `${$(8000)} a month is the CPF ordinary wage ceiling for 2026, the salary at which contributions reach their maximum. A citizen aged 30 pays ${$(r.monthly.employee)} and the employer ${$(r.monthly.employer)}, ${$(r.monthly.total)} in total; neither figure grows with any further raise. Take-home pay is ${$(r.takeHomeMonthly)}. From here, every extra dollar of salary reaches the bank account in full rather than at 80 cents. The ceiling also fixes the Additional Wage ceiling at its lowest possible level: ${$(r.awCeiling)} a year, since ${$(96000)} of ordinary wages already count towards the annual ${$(P.cpf.annual_salary_ceiling)}. Any bonus above ${$(r.awCeiling)} is paid without CPF. The CPF relief for tax is capped the same way, so taxable income rises faster than salary from this point: chargeable income is ${$(r.annual.chargeable)} and the YA ${P.tax.year_of_assessment} bill ${$(r.annual.tax)}.`,
      h2b: 'The ceiling has been raised in steps',
      p2: `The ordinary wage ceiling was ${$(6000)} until August 2023 and has been raised in stages to ${$(8000)} in 2026, to keep CPF adequate for middle-income earners. Each increase raised both contributions and employer costs for everyone at or above the old ceiling.`,
      faqs: [
        { q: 'What is the maximum CPF contribution per month in 2026?', a: `${$(r.monthly.total)} on ordinary wages for someone aged 55 or below, of which ${$(r.monthly.employee)} from the employee and ${$(r.monthly.employer)} from the employer. It is reached at the ${$(P.cpf.ow_ceiling_month)} ceiling. Additional wages such as a bonus can attract more, up to the Additional Wage ceiling.` },
        { q: 'Does a raise above $8,000 increase my CPF?', a: `Not on ordinary wages: contributions stop at the ${$(P.cpf.ow_ceiling_month)} ceiling, so a raise to ${$(9000)} leaves CPF at ${$(r.monthly.employee)} and adds the full ${$(1000)} to take-home pay, before income tax. Your bonus is still subject to CPF up to ${$(r.awCeiling)} a year.` },
        { q: 'How much tax on $8,000 a month in Singapore?', a: `${$(r.annual.tax)} for YA ${P.tax.year_of_assessment} for a citizen aged 30 with the automatic reliefs. Chargeable income is ${$(r.annual.chargeable)}, just below the ${$(80000)} point where the rate rises from 7 % to 11.5 %; a bonus would push part of the income into the 11.5 % band.` },
      ],
    }),
    10000: () => ({
      title: `$10,000 Salary Singapore 2026: Take-Home $8,400, 11.5 % Band`, description: `$10,000 a month in Singapore: ${$(r.takeHomeMonthly)} take-home, CPF capped at the $8,000 ceiling, tax of ${$(r.annual.tax)} in the 11.5 % band, and the reliefs that start to matter now.`,
      h1: `$10,000 a month in Singapore: take-home pay above the CPF ceiling`, h2: 'Into the 11.5 % band',
      p: `A salary of ${$(10000)} a month is above the CPF ceiling, so the employee contribution stays at ${$(r.monthly.employee)}, 16 % of salary rather than 20 %, and take-home pay is ${$(r.takeHomeMonthly)}. Income tax becomes a real item for the first time. Chargeable income for the year is ${$(r.annual.chargeable)}, past ${$(80000)}, where the resident rate rises from 7 % to 11.5 %. The YA ${P.tax.year_of_assessment} bill is ${$(r.annual.tax)}, about ${$(r.annual.tax / 12)} a month, and every additional dollar is taxed at 11.5 %. That is also the point at which voluntary reliefs start to pay: a ${$(15300)} contribution to the Supplementary Retirement Scheme would save about ${$(r.annual.tax - residentTax(r.annual.chargeable - 15300))} of tax this year, and a cash top-up of ${$(8000)} to your Special Account about ${$(r.annual.tax - residentTax(r.annual.chargeable - 8000))}.`,
      h2b: 'Foreign and local at $10,000',
      p2: `An Employment Pass holder on the same salary keeps the full ${$(10000)} each month and pays ${$(fo.annual.tax)} of tax as a resident, against ${$(r.annual.tax)} for the citizen, whose CPF relief lowers taxable income by ${$(r.annual.reliefs.cpf)}.`,
      faqs: [
        { q: 'How much tax on $120,000 a year in Singapore?', a: `${$(r.annual.tax)} for a citizen aged 30 paid ${$(10000)} a month without bonus, for YA ${P.tax.year_of_assessment}. Chargeable income after the earned income relief and CPF relief is ${$(r.annual.chargeable)}. A resident foreigner with no CPF pays ${$(fo.annual.tax)}, and a non-resident the higher of 15 % of gross pay and the resident scale.` },
        { q: 'Why is my CPF only 16 % of my $10,000 salary?', a: `Because CPF is charged only on the first ${$(P.cpf.ow_ceiling_month)} of monthly ordinary wages. 20 % of ${$(P.cpf.ow_ceiling_month)} is ${$(r.monthly.employee)}, which is 16 % of ${$(10000)}. The same ceiling limits your employer’s share to ${$(r.monthly.employer)}, so every raise above ${$(P.cpf.ow_ceiling_month)} reaches your take-home pay in full, before income tax.` },
        { q: 'Is SRS worth it on a $10,000 salary?', a: `It saves tax at your marginal rate, 11.5 % here. The maximum ${$(15300)} contribution for citizens and PRs would cut this year’s bill by about ${$(r.annual.tax - residentTax(r.annual.chargeable - 15300))}. The money is locked until the statutory retirement age, and half of each withdrawal is then taxed.` },
      ],
    }),
    12000: () => ({
      title: `$12,000 Salary Singapore 2026: Take-Home and 15 % Tax Band`, description: `$12,000 a month in Singapore: ${$(r.takeHomeMonthly)} take-home after capped CPF, YA 2027 tax of ${$(r.annual.tax)} with a 15 % marginal rate, and the gap with a foreign colleague.`,
      h1: `$12,000 a month: take-home pay and the 15 % marginal rate`, h2: 'A marginal rate of 15 %',
      p: `At ${$(12000)} a month, chargeable income for the year reaches ${$(r.annual.chargeable)} for a citizen aged 30, past ${$(120000)}, where the resident rate rises from 11.5 % to 15 %. The YA ${P.tax.year_of_assessment} bill is ${$(r.annual.tax)}, an effective rate of ${pct(r.annual.effectiveTaxRate)} on gross salary, and each extra dollar now costs 15 cents of tax. CPF has been capped since ${$(8000)}: the employee still pays ${$(r.monthly.employee)} a month, and take-home pay is ${$(r.takeHomeMonthly)}. Two things change at this level. Reliefs are worth more, since each dollar of relief saves 15 cents. And the bonus is taxed hard: a three-month bonus of ${$(36000)} attracts CPF on only ${$(6000)} and pushes part of the income into the 18 % band, costing ${$(c(12000, { bonus: 36000 }).annual.tax - r.annual.tax)} of extra tax.`,
      h2b: 'Employer cost at $12,000',
      p2: `The employer pays ${$(r.monthly.employer)} of CPF and ${$(P.sdl.max, 2)} of SDL each month, ${$(r.annual.employerCost)} a year in total, a surcharge of only ${pct(r.annual.employerCost / r.annual.gross - 1)} on salary because both are capped.`,
      faqs: [
        { q: 'What is $12,000 a month after tax in Singapore?', a: `${$(r.annual.net)} a year after CPF and income tax for a citizen aged 30, about ${$(r.annual.net / 12)} a month. The payslip shows ${$(r.takeHomeMonthly)} after CPF, and the YA ${P.tax.year_of_assessment} tax of ${$(r.annual.tax)} is paid the following year, often by GIRO in up to 12 monthly instalments.` },
        { q: 'At what salary do I reach the 15 % tax rate in Singapore?', a: `When chargeable income exceeds ${$(120000)}. For a citizen with only the automatic reliefs and no bonus, that happens at a salary of a little under ${$(12000)} a month; a bonus, or the absence of CPF relief for a foreigner, brings it lower.` },
        { q: 'How much tax does a foreigner pay on $12,000 a month?', a: `${$(fo.annual.tax)} for YA ${P.tax.year_of_assessment} as a tax resident, more than the citizen’s ${$(r.annual.tax)} because there is no CPF relief. A non-resident would pay the higher of 15 % of ${$(144000)} and the resident rates, which is ${$(c(12000, { status: 'FOREIGNER', taxResident: false }).annual.tax)}; residency depends on 183 days of presence or work in the year.` },
      ],
    }),
    15000: () => ({
      title: `$15,000 Salary Singapore 2026: Take-Home, Tax Near 18 % Band`, description: `$15,000 a month in Singapore: ${$(r.takeHomeMonthly)} take-home, ${$(r.annual.tax)} of tax for YA 2027 just below the 18 % band, and how the CPF and SDL caps shape the cost.`,
      h1: `$15,000 a month in Singapore: take-home pay and tax`, h2: 'Just below the 18 % band',
      p: `On ${$(15000)} a month, a citizen aged 30 has a chargeable income of ${$(r.annual.chargeable)} for the year, a few hundred dollars short of ${$(160000)}, where the resident rate moves from 15 % to 18 %. Any bonus therefore falls into the 18 % band, and above ${$(200000)} into the 19 % band. The YA ${P.tax.year_of_assessment} bill without bonus is ${$(r.annual.tax)}, an effective ${pct(r.annual.effectiveTaxRate)} of salary. CPF takes ${$(r.monthly.employee)} a month, the maximum since the ceiling, and take-home pay is ${$(r.takeHomeMonthly)}. For someone on this salary, the ${$(P.tax.relief_cap)} cap on reliefs starts to be relevant: CPF relief of ${$(r.annual.reliefs.cpf)}, a full SRS contribution, top-ups and family reliefs can add up quickly, and anything above the cap is lost. The tax saved by each dollar of relief, 15 to 18 cents, makes the choice of reliefs worth planning.`,
      h2b: 'A two-month bonus at this level',
      p2: `A ${$(30000)} bonus attracts CPF on ${$(6000)} only and adds ${$(c(15000, { bonus: 30000 }).annual.tax - r.annual.tax)} of tax, most of it at 18 %. Net of CPF and tax, ${$(30000 - (c(15000, { bonus: 30000 }).bonusMonth.employee - r.monthly.employee) - (c(15000, { bonus: 30000 }).annual.tax - r.annual.tax))} of the bonus reaches you.`,
      faqs: [
        { q: 'How much tax on $180,000 a year in Singapore?', a: `${$(r.annual.tax)} for YA ${P.tax.year_of_assessment} on ${$(15000)} a month without bonus, for a citizen aged 30. Chargeable income is ${$(r.annual.chargeable)}, just under ${$(160000)}: ${$(7950)} of tax on the first ${$(120000)} and 15 % on the rest, so the income stays in the 15 % band.` },
        { q: 'What is the take-home pay on $15,000 a month?', a: `${$(r.takeHomeMonthly)} for a citizen or PR from the third year aged 55 or below, since CPF stops at ${$(r.monthly.employee)} on the ${$(P.cpf.ow_ceiling_month)} ceiling. A foreign employee takes home the full ${$(15000)} and pays ${$(fo.annual.tax)} of tax as a resident, since without CPF there is no CPF relief.` },
        { q: 'Can I exceed the $80,000 relief cap on $15,000 a month?', a: `Only with many reliefs. CPF relief is ${$(r.annual.reliefs.cpf)}, SRS up to ${$(15300)}, cash top-ups up to ${$(16000)}, plus family reliefs. A parent with three children and dependent parents can approach ${$(P.tax.relief_cap)}; beyond it, extra reliefs give no further saving, so plan top-ups and SRS within the cap.` },
      ],
    }),
  };
  return A[m]();
}

export function annualAngle(y: number): Angle {
  const m = y / 12; const r = c(m); const fo = c(m, { status: 'FOREIGNER' }); const r13 = c(y / 13, { bonus: y / 13 });
  const A: Record<number, () => Angle> = {
    60000: () => ({
      title: `$60,000 Salary After Tax Singapore 2026: 12 or 13 Months`, description: `$60,000 a year in Singapore: ${$(r.annual.net)} after CPF and tax for a citizen, ${$(fo.annual.net)} for a foreigner, and why paying it over 12, 13 or 14 months barely matters.`,
      h1: `$60,000 salary after tax in Singapore`, h2: 'Twelve, thirteen or fourteen months',
      p: `${$(60000)} a year can be paid as ${$(5000)} over twelve months, about ${$(4615)} with a 13th month, or about ${$(4286)} with two extra months. For a citizen the structure makes almost no difference to the year: CPF is ${$(r.annual.cpfEmployee)} on twelve months and ${$(r13.annual.cpfEmployee)} with a 13th month, because at this salary the Additional Wage ceiling, ${$(r13.awCeiling)}, covers the whole bonus. Income tax for YA ${P.tax.year_of_assessment} is ${$(r.annual.tax)} either way, and the citizen keeps ${$(r.annual.net)} after CPF and tax. What changes is the monthly take-home: ${$(r.takeHomeMonthly)} on twelve months, ${$(r13.takeHomeMonthly)} on thirteen, with the difference arriving in December. A foreign employee on the same package keeps ${$(fo.annual.net)}: more cash, because no CPF is deducted, but ${$(fo.annual.tax)} of tax instead of ${$(r.annual.tax)}, because there is no CPF relief.`,
      h2b: 'Which structure to prefer',
      p2: `A 13-month structure smooths nothing for tax but makes the monthly budget tighter and the December payment larger. If the 13th month is contractual, the two are equivalent; if the bonus is discretionary, twelve fixed months are worth more.`,
      faqs: [
        { q: 'What is $60,000 a year after tax in Singapore?', a: `${$(r.annual.net)} for a citizen aged 30 after ${$(r.annual.cpfEmployee)} of CPF and ${$(r.annual.tax)} of income tax, about ${$(r.annual.net / 12)} a month. A foreigner keeps ${$(fo.annual.net)} because no CPF is deducted, though the foreigner’s tax is higher at ${$(fo.annual.tax)}, with no CPF relief to reduce it.` },
        { q: 'Is a 13th month bonus taxed more than monthly salary?', a: `No. Singapore taxes the year’s total income; how it is split between months does not change the rates. The 13th month counts as additional wages for CPF, but at ${$(60000)} a year the Additional Wage ceiling is ${$(r13.awCeiling)}, so CPF on it is the same as on salary.` },
        { q: 'What is the monthly salary for $60,000 a year?', a: `${$(5000)} a month if paid over twelve months, about ${$(4615)} over thirteen and about ${$(4286)} over fourteen. Take-home pay after 20 % CPF is ${$(r.takeHomeMonthly)}, ${$(r13.takeHomeMonthly)} and about ${$(c(y / 14, { bonus: y / 7 }).takeHomeMonthly)} a month respectively; the 13th and 14th months arrive with the December payslip in most companies.` },
      ],
    }),
    102000: () => ({
      title: `$102,000 Salary After Tax Singapore: The CPF Annual Ceiling`, description: `$102,000 is the CPF annual salary ceiling in 2026: above it no more CPF is due. Take-home, tax of ${$(r.annual.tax)} and what a citizen keeps after CPF and income tax.`,
      h1: `$102,000 a year: the CPF annual salary ceiling`, h2: 'The last dollar that attracts CPF',
      p: `${$(102000)} is the CPF annual salary ceiling in 2026: the maximum total wages, ordinary and additional, on which CPF contributions are due in a year. Ordinary wages are capped at ${$(8000)} a month, ${$(96000)} a year, and the remaining ${$(6000)} is the smallest possible room for bonuses. A citizen whose package is exactly ${$(102000)} and whose salary reaches the monthly ceiling pays the maximum CPF of the year, ${$(20400)} from the employee and ${$(17340)} from the employer, and nothing more on any additional income. On ${$(102000)} paid over twelve months, ${$(8500)} a month, the employee pays ${$(r.annual.cpfEmployee)} of CPF, take-home is ${$(r.takeHomeMonthly)} a month and YA ${P.tax.year_of_assessment} income tax ${$(r.annual.tax)}. Paid over thirteen months, CPF rises to ${$(r13.annual.cpfEmployee)} because the 13th month uses the Additional Wage ceiling, and tax falls to ${$(r13.annual.tax)} thanks to the extra CPF relief.`,
      h2b: 'Why the figure is $102,000',
      p2: `The annual limit equals the ordinary wage ceiling of ${$(8000)} times twelve plus ${$(6000)}. Contributions on it at 37 % give ${$(37740)}, which is also the annual CPF contribution limit for mandatory and voluntary contributions combined.`,
      faqs: [
        { q: 'What is the CPF annual salary ceiling in 2026?', a: `${$(102000)}. CPF is due on total wages up to that amount in a year: ordinary wages up to ${$(8000)} a month and additional wages up to the Additional Wage ceiling, which is ${$(102000)} minus the year’s ordinary wages subject to CPF. Above it, pay attracts no CPF.` },
        { q: 'What is $102,000 a year after tax in Singapore?', a: `${$(r.annual.net)} for a citizen aged 30 paid over twelve months, after ${$(r.annual.cpfEmployee)} of CPF and ${$(r.annual.tax)} of tax. Over thirteen months it is ${$(r13.annual.net)}, because more of the pay attracts CPF, which also lowers the tax. The difference is not lost: it sits in your CPF accounts.` },
        { q: 'How much CPF is paid at most in a year?', a: `${$(20400)} from an employee aged 55 or below and ${$(17340)} from the employer, ${$(37740)} in total, reached when total wages reach ${$(102000)}. That total is also the annual CPF contribution limit, which caps voluntary contributions on top, so someone already at the maximum cannot add voluntary contributions with tax relief.` },
      ],
    }),
    120000: () => ({
      title: `$120,000 Salary After Tax Singapore: Citizen vs Foreigner`, description: `$120,000 a year in Singapore: ${$(r.annual.net)} after CPF and tax for a citizen, ${$(fo.annual.net)} for a foreign resident. Monthly take-home, tax and how reliefs change it.`,
      h1: `$120,000 salary after tax: citizen versus foreigner`, h2: 'A typical expat package, compared',
      p: `${$(120000)} a year is a common package for experienced professionals, many of them foreigners on Employment Passes, and it shows the citizen-foreigner difference clearly. The foreign resident, with no CPF, takes home ${$(10000)} a month and pays ${$(fo.annual.tax)} of income tax for YA ${P.tax.year_of_assessment}, keeping ${$(fo.annual.net)} a year. The citizen contributes ${$(r.annual.cpfEmployee)} a year to CPF, takes home ${$(r.takeHomeMonthly)} a month, and pays ${$(r.annual.tax)} of tax thanks to the CPF relief, keeping ${$(r.annual.net)} in cash plus ${$(r.annual.cpfTotal)} in CPF with the employer’s share. The foreigner’s extra cash, ${$(fo.annual.net - r.annual.net)}, is smaller than the citizen’s total CPF: in wealth terms the citizen is ahead, in spending power the foreigner is. The citizen’s marginal rate is 11.5 %, the foreigner’s 15 %, which makes voluntary reliefs worth more to the foreigner.`,
      h2b: 'Reliefs a foreigner can use',
      p2: `A foreign resident can contribute up to ${$(35700)} a year to the Supplementary Retirement Scheme, more than the ${$(15300)} allowed to citizens and PRs, and claim spouse and child reliefs like anyone else. The SRS contribution alone would lower the foreigner’s tax by about ${$(fo.annual.tax - residentTax(fo.annual.chargeable - 35700))}.`,
      faqs: [
        { q: 'What is $120,000 after tax in Singapore for an expat?', a: `${$(fo.annual.net)} for a foreign tax resident with only the earned income relief: ${$(fo.annual.tax)} of tax for YA ${P.tax.year_of_assessment} and no CPF. A non-resident would pay 15 % of ${$(120000)}, ${$(18000)}, which is higher than the resident scale at this income.` },
        { q: 'How much does a citizen keep from $120,000 a year?', a: `${$(r.annual.net)} in cash after ${$(r.annual.cpfEmployee)} of CPF and ${$(r.annual.tax)} of tax, if paid over twelve months at age 30. Another ${$(r.annual.cpfTotal)} goes into CPF including the employer’s share, which the citizen can use for housing, healthcare and retirement, and which earns at least 2.5 % to 4 % a year.` },
        { q: 'How much can a foreigner put into SRS?', a: `Up to ${$(35700)} a year, against ${$(15300)} for citizens and PRs. Contributions are deductible in the year paid, within the ${$(P.tax.relief_cap)} relief cap, and withdrawals after the statutory retirement age are half taxable. A foreigner who leaves Singapore can withdraw after ten years without penalty.` },
      ],
    }),
    150000: () => ({
      title: `$150,000 Salary After Tax Singapore 2026: Net and 15 % Band`, description: `$150,000 a year in Singapore: ${$(r.annual.net)} after CPF and tax for a citizen, YA 2027 tax of ${$(r.annual.tax)} in the 15 % band, and what a bonus-heavy package changes.`,
      h1: `$150,000 salary after tax in Singapore`, h2: 'Fixed salary or a large bonus',
      p: `A ${$(150000)} package can be ${$(12500)} a month over twelve months, or a lower salary with a large bonus, and the split changes the outcome more than at lower incomes. Paid monthly, a citizen aged 30 contributes ${$(r.annual.cpfEmployee)} of CPF, pays ${$(r.annual.tax)} of tax for YA ${P.tax.year_of_assessment} at a 15 % marginal rate, and keeps ${$(r.annual.net)}. With ${$(10000)} a month and a ${$(30000)} bonus, CPF on the bonus is limited to the ${$(6000)} Additional Wage ceiling, so employee CPF becomes ${$(c(10000, { bonus: 30000 }).annual.cpfEmployee)} and tax ${$(c(10000, { bonus: 30000 }).annual.tax)}. The difference is the CPF relief on the extra ${$(6000)}. For the employer, a bonus-heavy structure reduces CPF cost only slightly, because ordinary wages above ${$(8000)} already attract none. For the employee, a fixed salary also counts fully in bank and HDB income assessments, while a bonus is often averaged or discounted.`,
      h2b: 'Where the next dollar goes',
      p2: `At this income each extra dollar of salary brings no CPF and 15 cents of tax. Chargeable income of ${$(r.annual.chargeable)} is ${$(160000 - r.annual.chargeable)} below the 18 % band, so a raise or bonus of that size stays at 15 %.`,
      faqs: [
        { q: 'What is $150,000 after tax in Singapore?', a: `${$(r.annual.net)} for a citizen aged 30 paid over twelve months, after ${$(r.annual.cpfEmployee)} of CPF and ${$(r.annual.tax)} of tax. A foreign resident keeps ${$(fo.annual.net)}, paying ${$(fo.annual.tax)} of tax but no CPF. The citizen also accumulates ${$(r.annual.cpfTotal)} in CPF with the employer’s share.` },
        { q: 'What is the marginal tax rate on $150,000?', a: `15 % for a citizen with the automatic reliefs, since chargeable income is ${$(r.annual.chargeable)}, between ${$(120000)} and ${$(160000)}. For a foreign resident without CPF relief, chargeable income is ${$(fo.annual.chargeable)}, which reaches the 15 % band as well, and a bonus would push part of it to 18 %.` },
        { q: 'Should I take a higher salary or a bigger bonus at $150,000?', a: `For CPF and tax the difference is small, because both are capped at this level. A fixed salary is certain and counts for mortgage applications; a bonus depends on performance. The Additional Wage ceiling of ${$(6000)} means most of a large bonus is paid without CPF.` },
      ],
    }),
  };
  return A[y]();
}

export function hourlyAngle(h: number): Angle {
  const m = monthlyFromHourly(h); const r = c(m); const pt = (hours: number) => c(m * hours / 44);
  const A: Record<number, () => Angle> = {
    12: () => ({
      title: `$12 an Hour Singapore 2026: Monthly Pay and Part-Time CPF`, description: `$12 an hour in Singapore is ${$(m)} a month full-time: take-home ${$(r.takeHomeMonthly)}, and how CPF phases in for part-timers working 8, 10 or 20 hours a week in 2026.`,
      h1: `$12 an hour in Singapore: full-time and part-time pay`, h2: 'Part-time hours and the CPF phase-in',
      p: `${$(12, 2)} an hour is a common rate for part-time retail, food and event work, and at that rate the number of hours decides how CPF applies. Full-time, 44 hours a week, it gives ${$(m)} a month on MOM’s formula, with the usual 20 % employee CPF and a take-home of ${$(r.takeHomeMonthly)}. At 20 hours a week, the month comes to about ${$(m * 20 / 44)}, above ${$(750)}, so the full rates apply and the employee keeps ${$(pt(20).takeHomeMonthly)}. At 10 hours a week, wages of about ${$(m * 10 / 44)} fall in the phase-in band between ${$(500)} and ${$(750)}: the employee pays only ${$(pt(10).monthly.employee)} and takes home ${$(pt(10).takeHomeMonthly)}. At 8 hours a week, about ${$(m * 8 / 44)} a month, the employee pays no CPF at all while the employer still contributes ${$(pt(8).monthly.employer)}. None of these levels owes income tax, and all of them count towards the employee’s CPF accounts through the employer’s share.`,
      h2b: 'The same rate for a full-time colleague',
      p2: `MOM’s guidance for paying part-timers the same rate as a monthly-paid colleague uses the same formula: the hourly rate is 12 × monthly pay ÷ (52 × 44). A full-time colleague on ${$(m)} a month and a part-timer on ${$(12, 2)} an hour are paid at the same rate.`,
      faqs: [
        { q: 'How much is $12 an hour per month in Singapore?', a: `${$(m)} a month for a full-time 44-hour week, using MOM’s formula of hourly rate × 52 × 44 ÷ 12, or ${$(m * 12)} a year. After 20 % employee CPF, a citizen takes home ${$(r.takeHomeMonthly)} a month. Working 20 hours a week gives about ${$(m * 20 / 44)} a month.` },
        { q: 'Does a part-timer on $12 an hour pay CPF?', a: `It depends on monthly earnings, not the rate. Below ${$(500)} a month only the employer contributes; between ${$(500)} and ${$(750)} the employee share phases in; above ${$(750)} the full 20 % applies. Eight hours a week at ${$(12, 2)} is about ${$(m * 8 / 44)} a month, with no employee CPF; ten hours a week, about ${$(m * 10 / 44)}, is in the phase-in band.` },
        { q: 'Is $12 an hour above the Local Qualifying Salary?', a: `The full-time equivalent, ${$(m)} a month, is above the ${$(W.lqs_monthly)} Local Qualifying Salary that applies from 1 July 2026. For part-time local workers, MOM sets an hourly equivalent for the quota computation; check the current figure with MOM if your employer counts you towards its foreign worker quota.` },
      ],
    }),
    20: () => ({
      title: `$20 an Hour Singapore 2026: Monthly Salary and Overtime`, description: `$20 an hour in Singapore equals ${$(m)} a month on MOM's formula: take-home ${$(r.takeHomeMonthly)}, tax ${$(r.annual.tax)}, and whether overtime at 1.5 times still applies to you.`,
      h1: `$20 an hour in Singapore: monthly salary and overtime`, h2: 'Whether overtime still applies',
      p: `At ${$(20, 2)} an hour, a full-time month is worth ${$(m)} on MOM’s formula, ${$(m * 12)} a year. That salary sits between the two overtime thresholds of Part IV of the Employment Act. A workman, doing manual work, is covered up to ${$(W.workman_ot_ceiling)} a month, so overtime at 1.5 times, ${$(30, 2)} an hour, is a legal right, within a cap of ${W.ot_hours_cap} overtime hours a month. An employee who is not a workman is covered only up to ${$(W.nonworkman_ot_ceiling)}, so at ${$(m)} overtime pay depends on the contract, not on the Act. For CPF, the citizen pays ${$(r.monthly.employee)} and takes home ${$(r.takeHomeMonthly)}; the employer adds ${$(r.monthly.employer)}. Income tax for the year is ${$(r.annual.tax)}, since chargeable income of ${$(r.annual.chargeable)} is in the 7 % band.`,
      h2b: 'Ten overtime hours a month',
      p2: `For a workman, ten hours of overtime at ${$(30, 2)} add ${$(300)} of ordinary wages to the month, which also attract 20 % CPF: ${$(60)} from the employee and ${$(51)} from the employer.`,
      faqs: [
        { q: 'What is $20 an hour in monthly salary in Singapore?', a: `${$(m)} a month for a full-time 44-hour week, based on MOM’s formula, or ${$(m * 12)} a year. A citizen aged 30 takes home ${$(r.takeHomeMonthly)} a month after CPF and owes about ${$(r.annual.tax)} of income tax for the year, while the employer adds ${$(r.monthly.employer)} a month of CPF.` },
        { q: 'Am I entitled to overtime at $20 an hour?', a: `If you are a workman, yes, because the monthly equivalent of ${$(m)} is below the ${$(W.workman_ot_ceiling)} limit of Part IV of the Employment Act; overtime is paid at ${$(30, 2)} an hour. If you are not a workman, the Act covers you only up to ${$(W.nonworkman_ot_ceiling)} a month, so it depends on your contract.` },
        { q: 'Is $20 an hour a good wage in Singapore?', a: `Its full-time equivalent, ${$(m)} a month, is below the median salary of about ${$(Math.round(grossFromMomMedian / 100) * 100)} implied by MOM’s 2025 figures, but well above the ${$(W.lqs_monthly)} Local Qualifying Salary. It is typical of skilled trade, technical and experienced service roles, and overtime can lift monthly earnings for workmen covered by the Employment Act.` },
      ],
    }),
    30: () => ({
      title: `$30 an Hour Singapore 2026: Salary and Freelance Rate`, description: `$30 an hour is ${$(m)} a month on MOM's formula in Singapore: take-home ${$(r.takeHomeMonthly)}, tax of ${$(r.annual.tax)}, and what the same rate is really worth to a freelancer.`,
      h1: `$30 an hour in Singapore: salary equivalent and freelance reality`, h2: 'Salaried at $30 or freelancing at $30',
      p: `An employee paid ${$(30, 2)} an hour on a full-time week earns ${$(m)} a month on MOM’s formula, ${$(m * 12)} a year. A citizen aged 30 contributes ${$(r.monthly.employee)} to CPF, takes home ${$(r.takeHomeMonthly)} and owes ${$(r.annual.tax)} of tax for YA ${P.tax.year_of_assessment}; the employer adds ${$(r.monthly.employer)} of CPF and SDL on top, and pays annual leave, sick leave and public holidays. A freelancer billing ${$(30, 2)} an hour is in a very different position: no employer CPF, no paid leave, and only the hours actually billed. Billing 1,500 hours a year, a realistic figure after gaps and admin, gives ${$(45000)} of fees, less than the salaried ${$(m * 12)} before even counting the employer’s CPF of ${$(r.annual.cpfEmployer)}. To match the employee’s full package, a freelancer would need to bill around ${$(Math.round(r.annual.employerCost / 1500))} an hour.`,
      h2b: 'Above the Employment Pass line',
      p2: `The monthly equivalent, ${$(m)}, is just above the ${$(W.ep_min)} Employment Pass qualifying salary for new applications, so a full-time role at this rate can be filled by a foreign professional who meets the other criteria.`,
      faqs: [
        { q: 'How much is $30 an hour per year in Singapore?', a: `${$(m * 12)} for a full-time 44-hour week, 52 weeks a year, or ${$(m)} a month. A citizen aged 30 takes home ${$(r.takeHomeMonthly)} a month after CPF and pays about ${$(r.annual.tax)} of tax a year; the employer adds ${$(r.monthly.employer)} a month of CPF.` },
        { q: 'What hourly rate should a freelancer charge to match a $5,720 salary?', a: `About ${$(Math.round(r.annual.employerCost / 1500))} an hour if you bill 1,500 hours a year, to cover the employer’s full cost of ${$(r.annual.employerCost)}, including CPF and SDL. Add more for insurance, equipment and unpaid gaps between contracts, since a freelancer has no paid leave, sick leave or public holidays.` },
        { q: 'Do freelancers pay CPF on $30 an hour?', a: 'Only MediSave, and only if their net trade income for the year exceeds $6,000. The CPF Board computes it from income and age after IRAS assesses the income. There is no compulsory contribution to the Ordinary or Special Account, and no employer share.' },
      ],
    }),
  };
  return A[h]();
}
